version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: consensus_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - consensus-network

  api:
    build:
      context: ..
      dockerfile: Dockerfile.api
    container_name: consensus_api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Production
      - Consensus__RedisConnectionString=redis:6379
      - Consensus__ApiEndpoint=${CONSENSUS_API_ENDPOINT}
      - Consensus__ApiKey=${CONSENSUS_API_KEY}
      - Cors__AllowedOrigins=http://localhost:5000
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - consensus-network

volumes:
  redis_data:
    driver: local

networks:
  consensus-network:
    driver: bridge
