using Consensus.Api.Models;

namespace Consensus.Api.Services;

/// <summary>
/// Service for reading log files generated by consensus jobs
/// </summary>
public interface ILogReader
{
    /// <summary>
    /// Read the log entries for a specific run
    /// </summary>
    /// <param name="runId">The run ID</param>
    /// <returns>List of log entries</returns>
    Task<IEnumerable<LogEntryModel>> ReadLogsAsync(string runId);
}
