namespace Consensus.Api.Services;

/// <summary>
/// Service for reading output files generated by consensus jobs
/// </summary>
public interface IOutputFileReaderService
{
    /// <summary>
    /// Read the HTML output file for a specific run
    /// </summary>
    /// <param name="runId">The run ID</param>
    /// <returns>The HTML content, or null if the file doesn't exist</returns>
    Task<string?> ReadHtmlAsync(string runId);
    
    /// <summary>
    /// Read the markdown output file for a specific run
    /// </summary>
    /// <param name="runId">The run ID</param>
    /// <returns>The markdown content, or null if the file doesn't exist</returns>
    Task<string?> ReadMarkdownAsync(string runId);
    
    /// <summary>
    /// Check if the HTML output file exists for a specific run
    /// </summary>
    /// <param name="runId">The run ID</param>
    /// <returns>True if the file exists</returns>
    bool HtmlExists(string runId);
    
    /// <summary>
    /// Check if the markdown output file exists for a specific run
    /// </summary>
    /// <param name="runId">The run ID</param>
    /// <returns>True if the file exists</returns>
    bool MarkdownExists(string runId);
}
